# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rwburke/ProjectEuler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rwburke/ProjectEuler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rwburke/ProjectEuler/CMakeFiles /home/rwburke/ProjectEuler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rwburke/ProjectEuler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/build
.PHONY : lib/fast

#=============================================================================
# Target rules for targets named 7

# Build rule for target.
7 : cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 7
.PHONY : 7

# fast build rule for target.
7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/7.dir/build.make CMakeFiles/7.dir/build
.PHONY : 7/fast

lib/functions.o: lib/functions.cpp.o
.PHONY : lib/functions.o

# target to build an object file
lib/functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/lib/functions.cpp.o
.PHONY : lib/functions.cpp.o

lib/functions.i: lib/functions.cpp.i
.PHONY : lib/functions.i

# target to preprocess a source file
lib/functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/lib/functions.cpp.i
.PHONY : lib/functions.cpp.i

lib/functions.s: lib/functions.cpp.s
.PHONY : lib/functions.s

# target to generate assembly for a file
lib/functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/lib/functions.cpp.s
.PHONY : lib/functions.cpp.s

lib/prime.o: lib/prime.cpp.o
.PHONY : lib/prime.o

# target to build an object file
lib/prime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/lib/prime.cpp.o
.PHONY : lib/prime.cpp.o

lib/prime.i: lib/prime.cpp.i
.PHONY : lib/prime.i

# target to preprocess a source file
lib/prime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/lib/prime.cpp.i
.PHONY : lib/prime.cpp.i

lib/prime.s: lib/prime.cpp.s
.PHONY : lib/prime.s

# target to generate assembly for a file
lib/prime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/lib/prime.cpp.s
.PHONY : lib/prime.cpp.s

solutions/7/7.o: solutions/7/7.cpp.o
.PHONY : solutions/7/7.o

# target to build an object file
solutions/7/7.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/7.dir/build.make CMakeFiles/7.dir/solutions/7/7.cpp.o
.PHONY : solutions/7/7.cpp.o

solutions/7/7.i: solutions/7/7.cpp.i
.PHONY : solutions/7/7.i

# target to preprocess a source file
solutions/7/7.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/7.dir/build.make CMakeFiles/7.dir/solutions/7/7.cpp.i
.PHONY : solutions/7/7.cpp.i

solutions/7/7.s: solutions/7/7.cpp.s
.PHONY : solutions/7/7.s

# target to generate assembly for a file
solutions/7/7.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/7.dir/build.make CMakeFiles/7.dir/solutions/7/7.cpp.s
.PHONY : solutions/7/7.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 7"
	@echo "... lib"
	@echo "... lib/functions.o"
	@echo "... lib/functions.i"
	@echo "... lib/functions.s"
	@echo "... lib/prime.o"
	@echo "... lib/prime.i"
	@echo "... lib/prime.s"
	@echo "... solutions/7/7.o"
	@echo "... solutions/7/7.i"
	@echo "... solutions/7/7.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

